<?php

namespace ManiaLivePlugins\eXpansion\Menu\Gui\Widgets;

use ManiaLib\Gui\Elements\Frame;
use ManiaLib\Gui\Elements\Quad;
use ManiaLib\Gui\Layouts\Column;

class MenuWidget extends \ManiaLivePlugins\eXpansion\Gui\Widgets\PlainWidget
{
    public $items = [];
    protected $frame;
    protected $script;

    protected function onConstruct()
    {
        parent::onConstruct();

        $this->frame = new \ManiaLive\Gui\Controls\Frame(0, 0, new Column(50, 20));
        $this->frame->setId("Menu");
        $this->addComponent($this->frame);

        $this->script = new \ManiaLivePlugins\eXpansion\Gui\Structures\Script("Menu\Gui\Script");

        $storage = \ManiaLive\Data\Storage::getInstance();
        $this->script->setParam("name", "Submenu");
        $this->script->setParam("gameMode", \ManiaLivePlugins\eXpansion\Gui\Gui::fixString($storage->gameInfos->scriptName));
        $this->script->setParam("forceReset", $this->getBoolean(DEBUG));
        $this->registerScript($this->script);
    }

    public function addGroup($name)
    {
        $this->items[] = 1;
        $group = new \ManiaLivePlugins\eXpansion\Menu\Gui\Controls\GroupItem($name, count($this->items));
        $this->frame->addComponent($group);
        return $group;
    }

    public function onShow()
    {
        $this->script->setParam("itemCount", count($this->items));
        parent::onShow(); // TODO: Change the autogenerated stub
    }

    public function addItem($itemName, $handle, $plugin)
    {
        $action = $this->createAction(array($plugin, "actionHandler"), $handle);
        $this->items[] = 1;
        /* @var $config \ManiaLivePlugins\eXpansion\Gui\Config */
        $config = \ManiaLivePlugins\eXpansion\Gui\Config::getInstance();

        $frame = new \ManiaLive\Gui\Controls\Frame();
        $frame->setSize(30,5);

        /* @var $label \ManiaLivePlugins\eXpansion\Gui\Elements\DicoLabel */
        $label = new \ManiaLivePlugins\eXpansion\Gui\Elements\DicoLabel(30, 5);
        $label->setText(eXpGetMessage($itemName));
        $label->setId("item_" . count($this->items));
        $label->setAttribute("class", "menu item");
        $label->setPosX(2);
        $label->setTextSize(1);
        $label->setStyle("TextRaceChat");
        $label->setTextColor("fff");
        $label->setAlign("left", "center");
        //$label->setAction($action);

        $quad = new Quad(30, 5);
        $quad->setBgcolor($config->style_widget_bgColorize);
        $quad->setBgcolorFocus($config->style_widget_title_bgColorize);
        $quad->setId("mQuad_" . count($this->items));
        $quad->setAlign("left", "center");
        $quad->setScriptEvents();
        $quad->setAction($action);

        $frame->addComponent($quad);
        $frame->addComponent($label);

        $this->frame->addComponent($frame);
    }
}
