<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Phine\\Phar' => array($vendorDir . '/phine/phar/src/lib'),
    'Phine\\Path' => array($vendorDir . '/phine/path/src/lib'),
    'Phine\\Observer' => array($vendorDir . '/phine/observer/src/lib'),
    'Phine\\Exception' => array($vendorDir . '/phine/exception/src/lib'),
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
);
