<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'oliverde8\\AsynchronousJobs\\' => array($vendorDir . '/oliverde8/asynchronous-jobs/src/AsynchronousJobs'),
    'Maniaplanet\\' => array($vendorDir . '/maniaplanet/dedicated-server-api/libraries/Maniaplanet', $vendorDir . '/maniaplanet/maniaplanet-ws-sdk/libraries/Maniaplanet'),
    'ManiaLive\\' => array($vendorDir . '/maniaplanet/manialive-lib/ManiaLive'),
    'ManiaLivePlugins\\eXpansion\\' => array($vendorDir . '/ml-expansion/expansion'),
);
